name: pylint

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  run_pylint:
    runs-on: ubuntu-22.04
    env:
      pylint_version: 2.13.9
    strategy:
      matrix:
        py-version: [3.7, 3.8, 3.9] # When EL8 is gone, we can remove everything up to 3.9
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.7-3.9
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.py-version }}
    - name: Install pylint
      run: |
        python3 -m pip install --upgrade pip
        pip install pylint==$pylint_version
    - name: Run pylint on code (lib)
      run: pylint --rcfile=.pylintrc lib/*
    - name: Run pylint on code (bin)
      run: pylint --rcfile=.pylintrc --ignore=condor_vault_storer bin/*
